### ISSUE TITLE
Dreiding umbrella functional form

### ISSUE THREAD

**Issue by danstine** [polysimtools/pysimm#18]
The current pysimm version has the Dreiding FF with the harmonic improper style. The original paper suggests using the umbrella functional form for impropers. The results from both styles are similar but can lead to slight differences in structure. Is it possible to change the Dreiding force constants to be consistent with the umbrella style functional form from the original paper and then modify the lammps module to generate umbrella style inputs?

Thank you.

**Comment by mefortunato** [comment]
Both of these functional forms should maintain planarity for impropers with an equilibrium angle defined at 0. We'll update to use the umbrella style in LAMMPS as described in the original Dreiding paper.

The force constant should be changed to 40 kca/mol in the forcefield data file, and the style name should be changed to umbrella. The formatting of data in LAMMPS data files doesn't need to change much since the number and order of parameters doesn't change.
